// Build `src/data/github.yml` — the current-year GitHub contribution count.
//
// Uses a PUBLIC, TOKEN-FREE contributions API (jogruber), reading the username
// from profile.yml (socials.githubUser). No PAT / secret required, so it works
// in CI out of the box. Run `npm run build:github` or let the github workflow
// refresh it on schedule.
//
// Best-effort: if the request fails, it keeps the existing github.yml untouched
// so the site never loses its last-known count.

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";

const ROOT = path.resolve(fileURLToPath(import.meta.url), "../..");
const OUT_FILE = path.join(ROOT, "src", "data", "github.yml");
const PROFILE = path.join(ROOT, "src", "data", "profile.yml");

const HEADER =
  "# Generated by scripts/build-github.mjs from a public contributions API.\n" +
  "# Do not edit by hand — run `npm run build:github` (no token needed) or let\n" +
  "# the github workflow refresh it on schedule.\n";

async function readYaml(file) {
  try {
    return parseYaml(await readFile(file, "utf8"));
  } catch {
    return undefined;
  }
}

async function main() {
  const profile = await readYaml(PROFILE);
  const username = profile?.profile?.socials?.githubUser;
  if (!username) {
    console.warn("[github] no socials.githubUser in profile.yml — skipping");
    return;
  }

  const year = new Date().getUTCFullYear();
  const url = `https://github-contributions-api.jogruber.de/v4/${username}?y=${year}`;

  let total;
  try {
    const res = await fetch(url, {
      headers: { "User-Agent": "rohit-portfolio-build" },
    });
    if (!res.ok) {
      console.warn(`[github] HTTP ${res.status} — keeping existing github.yml`);
      return;
    }
    const json = await res.json();
    total = json?.total?.[year] ?? json?.total?.[String(year)];
  } catch (err) {
    console.warn("[github] fetch failed — keeping existing github.yml:", err);
    return;
  }

  if (typeof total !== "number") {
    console.warn("[github] no count in response — keeping existing github.yml");
    return;
  }

  const existing = (await readYaml(OUT_FILE))?.contributions;
  if (existing === total) {
    console.log(`[github] unchanged (${total} contributions in ${year})`);
    return;
  }

  await writeFile(OUT_FILE, HEADER + stringifyYaml({ contributions: total }));
  console.log(
    `[github] wrote ${path.relative(ROOT, OUT_FILE)} (${total} in ${year})`,
  );
}

main();
