// Build `src/data/github.yml` from the GitHub GraphQL API.
//
// Queries viewer.contributionsCollection.contributionCalendar.totalContributions
// with a fine-grained PAT in GITHUB_TOKEN, and writes the count to github.yml.
// Run `npm run build:github` locally (GITHUB_TOKEN in .env / shell) or let the
// github workflow refresh it on a schedule.
//
// Best-effort: if the token is missing or the request fails, it keeps the
// existing github.yml untouched so the site never loses its last-known count.

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";

const ROOT = path.resolve(fileURLToPath(import.meta.url), "../..");
const OUT_FILE = path.join(ROOT, "src", "data", "github.yml");

const HEADER =
  "# Generated by scripts/build-github.mjs from the GitHub GraphQL API.\n" +
  "# Do not edit by hand — run `npm run build:github` (needs GITHUB_TOKEN) or let\n" +
  "# the github workflow refresh it on schedule.\n";

async function existingCount() {
  try {
    return parseYaml(await readFile(OUT_FILE, "utf8"))?.contributions;
  } catch {
    return undefined;
  }
}

async function main() {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    console.warn("[github] no GITHUB_TOKEN — keeping existing github.yml");
    return;
  }

  let total;
  try {
    const res = await fetch("https://api.github.com/graphql", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
        "User-Agent": "rohit-portfolio-build",
      },
      body: JSON.stringify({
        query: `{ viewer { contributionsCollection {
          contributionCalendar { totalContributions } } } }`,
      }),
    });
    if (!res.ok) {
      console.warn(`[github] HTTP ${res.status} — keeping existing github.yml`);
      return;
    }
    const json = await res.json();
    total =
      json?.data?.viewer?.contributionsCollection?.contributionCalendar
        ?.totalContributions;
  } catch (err) {
    console.warn("[github] fetch failed — keeping existing github.yml:", err);
    return;
  }

  if (typeof total !== "number") {
    console.warn("[github] no count in response — keeping existing github.yml");
    return;
  }

  const prev = await existingCount();
  if (prev === total) {
    console.log(`[github] unchanged (${total} contributions)`);
    return;
  }

  await writeFile(OUT_FILE, HEADER + stringifyYaml({ contributions: total }));
  console.log(`[github] wrote ${path.relative(ROOT, OUT_FILE)} (${total})`);
}

main();
