// Shared build-time YAML loader for the data layer.
//
// All content lives in src/data/*.yml (hand-edited, or generated by a script
// like build-health.mjs / build-github.mjs). Each *.ts accessor reads its YAML
// through this helper and exposes typed exports, so components never touch the
// data format. Reads are synchronous — this only ever runs at build time.
//
// On any read/parse error it returns the provided fallback and warns, so a
// missing or malformed file can never break the build (portfolio rule #2).

import { readFileSync } from "node:fs";
import path from "node:path";
import { parse as parseYaml } from "yaml";

export function loadYaml<T>(fileName: string, fallback: T): T {
  try {
    const file = path.resolve(process.cwd(), "src/data", fileName);
    const data = parseYaml(readFileSync(file, "utf8")) as T | null;
    return data ?? fallback;
  } catch (err) {
    console.warn(`[data] could not read ${fileName} — using fallback:`, err);
    return fallback;
  }
}
