// GitHub contributions for the current year.
//
// SOURCE: src/data/github.yml, generated by scripts/build-github.mjs which
// queries the GitHub GraphQL API (viewer.contributionsCollection
// .contributionCalendar.totalContributions) with a fine-grained PAT. Run
// `npm run build:github` (needs GITHUB_TOKEN) or let the github workflow
// refresh it on a schedule — same "update the YAML" model as health.
//
// This accessor just reads the YAML, falling back to a last-known count so the
// build never breaks (rule #2).

import { loadYaml } from "./_load";

interface GitHubFile {
  contributions: number;
}

const FALLBACK = 1284;

export function getContributions(): number {
  const data = loadYaml<GitHubFile>("github.yml", { contributions: FALLBACK });
  return typeof data.contributions === "number"
    ? data.contributions
    : FALLBACK;
}
